### ISSUE TITLE
Cenário Atual do Cliente e do Negócio

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-IdeaSpace#3]
Problema: "escassez de engajamento do aluno". Falta de engajamento?
É preciso rever e ajustar o problema.
Avaliar se todas as causas são resolvíveis por software, caso contrário, informar quais as causas serão, de fato, sanadas com o software.

**Comment by MatheussBrant** [comment]
@phmelosilva

**Comment by phmelosilva** [comment]
@MatheussBrant Está bem mais condizente com um produto de software.
