### ISSUE TITLE
Cronograma e Entregas

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.2-T01-IdeaSpace#5]
**Considerações:**

- [x] Período de Festas: A sprint 4 ocorrem durante o período de festas de final de ano (26/12/2024 a 08/01/2025).

**Comment by MatheussBrant** [comment]
@phmelosilva

**Comment by phmelosilva** [comment]
@MatheussBrant Cronograma está mais organizado para a realidade da equipe.
